In [ ]:
# 列表推导式的结合
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_list = [ number for row in list_of_lists for number in row]
print(flattened_list)    # [1, 2, 3, 4, 5, 6, 7, 8, 9]

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
# lamdba函数的使用
(lambda a,b: a + b)

<function __main__.<lambda>(a, b)>

In [4]:
print((lambda a,b: a + b)(2,3))

5


In [ ]:
square = lambda x:x ** 2
print(square(3))

9


In [8]:
mul = lambda a,b,c : a ** 2 - 3 * b + 4 * c
print(mul(5,5,3))

22


In [11]:
# Filter only negative and zero in the list using list comprehension
# 使用列表推导式仅过滤列表中的负值和零

numbers = [-4, -3, -2, -1, 0, 2, 4, 6]
res = [row for row in numbers if row >0]
res

[2, 4, 6]

In [15]:
# Flatten the following list of lists of lists to a one dimensional list :
# 将以下列表列表拼合为一维列表：

list_of_lists =[[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]]

# output
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
res = [m for row in list_of_lists for n in row for m in n ]
res

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
# Using list comprehension create the following list of tuples:
# 使用列表推导式创建以下 Tuples 列表：

[(0, 1, 0, 0, 0, 0, 0),
(1, 1, 1, 1, 1, 1, 1),
(2, 1, 2, 4, 8, 16, 32),
(3, 1, 3, 9, 27, 81, 243),
(4, 1, 4, 16, 64, 256, 1024),
(5, 1, 5, 25, 125, 625, 3125),
(6, 1, 6, 36, 216, 1296, 7776),
(7, 1, 7, 49, 343, 2401, 16807),
(8, 1, 8, 64, 512, 4096, 32768),
(9, 1, 9, 81, 729, 6561, 59049),
(10, 1, 10, 100, 1000, 10000, 100000)]

res = [(row,row ** 0,row,row ** 2,row ** 3,row ** 4,row ** 5) for row in range(11) ]
print(res)
res = [(row,) + tuple(row ** x for x in range(6)) for row in range(11)]
print(res)


[(0, 1, 0, 0, 0, 0, 0), (1, 1, 1, 1, 1, 1, 1), (2, 1, 2, 4, 8, 16, 32), (3, 1, 3, 9, 27, 81, 243), (4, 1, 4, 16, 64, 256, 1024), (5, 1, 5, 25, 125, 625, 3125), (6, 1, 6, 36, 216, 1296, 7776), (7, 1, 7, 49, 343, 2401, 16807), (8, 1, 8, 64, 512, 4096, 32768), (9, 1, 9, 81, 729, 6561, 59049), (10, 1, 10, 100, 1000, 10000, 100000)]
[(0, 1, 0, 0, 0, 0, 0), (1, 1, 1, 1, 1, 1, 1), (2, 1, 2, 4, 8, 16, 32), (3, 1, 3, 9, 27, 81, 243), (4, 1, 4, 16, 64, 256, 1024), (5, 1, 5, 25, 125, 625, 3125), (6, 1, 6, 36, 216, 1296, 7776), (7, 1, 7, 49, 343, 2401, 16807), (8, 1, 8, 64, 512, 4096, 32768), (9, 1, 9, 81, 729, 6561, 59049), (10, 1, 10, 100, 1000, 10000, 100000)]


In [47]:
# Flatten the following list to a new list:
# 将以下列表拼合为新列表：
# output:
# [['FINLAND','FIN', 'HELSINKI'], ['SWEDEN', 'SWE', 'STOCKHOLM'], ['NORWAY', 'NOR', 'OSLO']]

countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]]
# myres
res = [[m[0]] + [m[0][:3]] + [m[1]]  for row in countries for m in row for n in m]
res
# gptres
res = [[c1,c1[:3],c2] for [(c1,c2)] in countries ]
res

[['Finland', 'Fin', 'Helsinki'],
 ['Sweden', 'Swe', 'Stockholm'],
 ['Norway', 'Nor', 'Oslo']]

In [48]:
# Change the following list to a list of dictionaries:
# 将以下列表更改为词典列表：
# output:
# [{'country': 'FINLAND', 'city': 'HELSINKI'},
# {'country': 'SWEDEN', 'city': 'STOCKHOLM'},
# {'country': 'NORWAY', 'city': 'OSLO'}]
countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]]
res =[dict(country = c1 , city = c2) for [(c1,c2)] in countries]

res

[{'country': 'Finland', 'city': 'Helsinki'},
 {'country': 'Sweden', 'city': 'Stockholm'},
 {'country': 'Norway', 'city': 'Oslo'}]

In [50]:
# Change the following list of lists to a list of concatenated strings:
# 将以下列表列表更改为串联字符串列表：
# output
# ['Asabeneh Yetaeyeh', 'David Smith', 'Donald Trump', 'Bill Gates']

names = [[('Asabeneh', 'Yetayeh')], [('David', 'Smith')], [('Donald', 'Trump')], [('Bill', 'Gates')]]
res = [a +' '+ b for [(a,b)] in names]
res 

['Asabeneh Yetayeh', 'David Smith', 'Donald Trump', 'Bill Gates']

In [58]:
# Write a lambda function which can solve a slope or y-intercept of linear functions.
# 编写一个 lambda 函数，该函数可以求解线性函数的斜率或 y 截距。

# 设函数形式伟为：a * x + b * y + c = 0,其中b不能等于0
la_k = lambda a,b,c : -(a/b)
la_b = lambda a,b,c : -(c/b)
res1 = la_k(1,2,3)
res2 = la_b(1,2,3)
print(res1,res2)

# 确立两点(x1,y1)(x2,y2)
solve_linear = lambda points, find : (lambda x1 , y1 , x2, y2: (y2 - y1) / (x2 - x1) if find == "slope" else y1 - ((y2 - y1)/(x2 - x1))* x1)(*points)
# Example usage
points = (1, 2, 3, 6)  # Two points: (1, 2) and (3, 6)
slope = solve_linear(points, "slope")  # Calculate slope
y_intercept = solve_linear(points, "y_intercept")  # Calculate y-intercept

print("Slope:", slope)
print("Y-Intercept:", y_intercept)


-0.5 -1.5
Slope: 2.0
Y-Intercept: 0.0


In [61]:
points = (1, 2, 3, 6)

# 解包元组
x1, y1, x2, y2 = points
print(x1, y1, x2, y2)  # 输出: 1 2 3 6

def print_points(x1, y1, x2, y2):
    print(f"Point 1: ({x1}, {y1}), Point 2: ({x2}, {y2})")

points = (1, 2, 3, 6)

# 使用 * 解包元组
print_points(*points)  # 输出: Point 1: (1, 2), Point 2: (3, 6)
print(*points)

1 2 3 6
Point 1: (1, 2), Point 2: (3, 6)
1 2 3 6


In [ ]:
'''
高级函数：
函数作为参数 - 函数作为返回值
闭包：一个函数嵌套在另一个封装函数中，然后返回内部函数
def a():
  def b():
    return :xx
  return b
装饰器：可以不修改函数结构，并添加新功能
'''

In [66]:
# 装饰器
def greeting(): # 普通函数
  return 'Welcome to Beijing'
def uppercase_decorator(function):  
  def wrapper():
    func = function()
    make_uppercase = func.upper()
    return make_uppercase
  return wrapper
  
g = uppercase_decorator(greeting)
print(g())


WELCOME TO BEIJING


In [ ]:
# 错误类型
# SyntaxError 语法错误
# 名称错误 名称错误
# IndexError 索引错误
# ModuleNotFoundError
# AttributeError 属性错误
# KeyError  获取 dictionary 值的 key 中存在拼写错误
# TypeError 类型错误

# ZeroDivisionError  零除法错误


In [70]:
# 异常处理
try:
    name = input('Enter your name:')
    year_born = input('Year you born:')
    age = 2019 - int(year_born)
    print(f'You are {name}. And your age is {age}.')
except TypeError:
    print('Type error occur')
except ValueError:
    print('Value error occur')
except ZeroDivisionError:
    print('zero division error occur')
else:
    print('I usually run with the try block')
finally:
    print('I alway run.')

Value error occur
I alway run.


In [ ]:
# 简写
try:
    name = input('Enter your name:')
    year_born = input('Year you born:')
    age = 2019 - int(year_born)
    print(f'You are {name}. And your age is {age}.')
except Exception as e:
    print(e)



invalid literal for int() with base 10: 'gsdg'


# Statistics Module
## NumPy

In [71]:
import numpy as np

print('numpy:',np.__version__)
print(dir(np))

numpy: 1.24.3
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '

In [ ]:
p_list =[1,2,3,4,5]
print('Type',type(p_list))
print(p_list)

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

numpy_array_from_list = np.array(p_list)
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])


Type <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
# Python list
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)  # float numpy 数组
print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


In [ ]:
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool) # 布尔 numpy 数组
print(numpy_bool_array) # array([False,  True,  True, False, False])

[False  True  True False False]


In [ ]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]  # 多维数组
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
# We can always convert an array back to a python list using tolist().将数组转换为list
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [80]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple) # numpy_array_from_tuple:  [1 2 3 4 5]

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [ ]:
num = np.array([1,2,3,4,5])
print(num)
print('shape of nums:',num.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
    [4,5,6,7],
    [8,9,10, 11]])
print(three_by_four_array.shape)


[1 2 3 4 5]
shape of nums: (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


In [84]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)


[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


In [85]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) # 5
print('The size:', two_dimensional_list.size)  # 3


The size: 5
The size: 9


In [86]:
# Mathematical Operation
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)


original array:  [1 2 3 4 5]
[11 12 13 14 15]


In [87]:
# Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


In [88]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


In [89]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [90]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


In [91]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 0 0 0]


In [92]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


In [93]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


In [94]:
numpy_str_arr = numpy_int_arr.astype('str')
print(numpy_str_arr)

['1' '2' '3' '4']


In [ ]:
# 2 Dimension Array
# 获取多维数组 行

two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


In [ ]:
# 获取多维数组 列

first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)


First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


In [ ]:

two_dimension_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(two_dimension_array[::-2,::-2])
print(two_dimension_array[::-1,::-1])


[[9 7]
 [3 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] = 44
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [ ]:
# Numroespy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_ze

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [122]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Numpy Ones
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [124]:
twoes = numpy_ones * 2
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [127]:
# Reshape
# numpy.reshape(), numpy.flatten()
# 修改数组大小
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

flattened = reshaped.flatten()
flattened


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [129]:
## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [130]:
# Generate a random float  number
random_float = np.random.random()
random_float

0.4944978629430884

In [138]:
# Generate a random float  number
random_floats = np.random.random(5)
random_floats

array([0.64720486, 0.47178739, 0.21297398, 0.52299385, 0.36262957])

In [136]:
# Generating a random integers between 0 and 10

random_int = np.random.randint(0, 48)
random_int

37

In [139]:
# Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size=4)
random_int

array([5, 9, 9, 8])

In [140]:
# Generating a random integers between 0 and 10
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[5, 9, 7],
       [2, 3, 4],
       [3, 9, 7]])

In [142]:
# np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 4)
normal_array


array([54.10553371, 75.20612318, 72.47222925, 83.29768934])

In [143]:
normal_array = np.random.normal(79, 15, (2,2))
normal_array

array([[ 85.62638839,  83.73793583],
       [101.5970549 ,  98.48636148]])